#:import get_color_from_hex kivy.utils.get_color_from_hex

#:set text_color get_color_from_hex("#4a4939")
#:set focus_color get_color_from_hex("#e7e4c0")
#:set ripple_color get_color_from_hex("#c5bdd2")
#:set bg_color get_color_from_hex("#f7f4e7")
#:set selected_color get_color_from_hex("#0c6c4d")

<MyItem>
    text: "Book"
    secondary_text: "Chapter"
    tertiary_text: "Verse"
    _no_ripple_effect: True


<DrawerClickableItem@MDNavigationDrawerItem>
    focus_color: focus_color
    unfocus_color: bg_color
    text_color: text_color
    icon_color: text_color
    ripple_color: ripple_color
    selected_color: selected_color


<DrawerLabelItem@MDNavigationDrawerItem>
    bg_color: bg_color
    text_color: text_color
    icon_color: text_color
    _no_ripple_effect: True

<MD3Card>
    padding: 16
    size_hint: None, None
    md_bg_color: bg_color
    #size: self.minimum_size
    size: str(len(root.text)*4)+"dp",str(len(root.text)*1.8)+"dp"
    #size: content.size
    pos_hint: {"center_x": .5, "center_y": .5}

    MDRelativeLayout:
        size_hint: None, None
        size: root.size

        MDIconButton:
            icon: "dots-vertical"
            pos:
                root.width - (self.width + root.padding[0] + dp(4)), root.height - (self.height + root.padding[0] + dp(4))

        MDLabel:
            id: label
            text: root.text
            color: .2, .2, .2, .8



MDScreen:

    MDToolbar:
        id: toolbar
        #title: "The last word"
        elevation: 10
        pos_hint: {"top": 1}
        md_bg_color: focus_color
        specific_text_color: text_color
        left_action_items:
            [['menu', lambda x:nav_drawer.set_state("open")  if nav_drawer.state == "close" else nav_drawer.set_state("close")  ]  ]

    MDNavigationLayout:
        x: toolbar.height
        ScreenManager:

            id: screen_manager
            MDScreen:


            MDScreen:
                name: "bible_scr"

                MDBoxLayout:
                    orientation: "vertical"

                    MDToolbar:
                        id: toolbar
                        title: "KJV"

                    ScrollView:

                        MDSelectionList:
                            id: selection_list
                            overlay_color: app.overlay_color[:-1] + [.2]
                            icon_bg_color: app.overlay_color
                            icon_pos : [-50,0]
                            on_selected: app.on_selected(*args)
                            on_unselected: app.on_unselected(*args)
                            on_selected_mode: app.set_selection_mode(*args)
                            progress_round_size:0


                #MDLabel:
                #    text: "Read Bible"
                #    halign: "center"

                MDFloatingActionButtonSpeedDial:
                    data: app.data
                    icon: "dots-horizontal"
                    bg_color_root_button: text_color
                    bg_color_stack_button: text_color
                    bg_hint_color: bg_color
                    hint_animation: True

            MDScreen:
                name: "verse_today_scr"

                #MDLabel:
                #    text: app.verse_today
                #    theme_text_color: "Custom"
                #    text_color: text_color
                #    halign: "center"

                MDBoxLayout:
                    id: box
                    #adaptive_height: True
                    adaptive_size: True
                    spacing: "56dp"
                    pos_hint: {"center_x": .5, "center_y": .5}

            MDScreen:
                name: "tools_scr"

                MDLabel:
                    text: "Tools"
                    halign: "center"

            MDScreen:
                name: "theming_scr"

                MDLabel:
                    text: "Theming"
                    halign: "center"

            MDScreen:
                name: "setting_scr"

                MDLabel:
                    text: "Settings"
                    halign: "center"

        MDNavigationDrawer:
            id: nav_drawer
            radius: (0, 16, 16, 0) if self.anchor == "left" else (16, 0, 0, 16)
            md_bg_color: bg_color

            MDNavigationDrawerMenu:

                MDNavigationDrawerHeader:
                    title: "The Last Word"
                    title_color: text_color
                    #text: "v 1.0"
                    title_color: text_color
                    spacing: "4dp"
                    padding: "12dp", 0, 0, "56dp"

                MDNavigationDrawerLabel:
                    text: "Bible Menu"

                DrawerClickableItem:
                    icon: "book"
                    #right_text: "+99"
                    text_right_color: text_color
                    text: "Read"
                    on_press:
                        toolbar.title = "Read"
                        nav_drawer.set_state("close")
                        screen_manager.current = "bible_scr"

                DrawerClickableItem:
                    icon: "send"
                    text: "Today Verse"
                    on_press:
                        toolbar.title = "Today Verse"
                        nav_drawer.set_state("close")
                        screen_manager.current = "verse_today_scr"

                MDNavigationDrawerDivider:

                MDNavigationDrawerLabel:
                    text: "Misc"

                DrawerClickableItem:
                    icon: "cog"
                    #right_text: "+99"
                    text_right_color: text_color
                    text: "Settings"
                    on_press:
                        toolbar.title = "Settings"
                        nav_drawer.set_state("close")
                        screen_manager.current = "setting_scr"

                DrawerClickableItem:
                    icon: "shape"
                    text: "Theme"
                    on_press:
                        toolbar.title = "Theme"
                        nav_drawer.set_state("close")
                        screen_manager.current = "theming_scr"

                DrawerClickableItem:
                    icon: "tools"
                    text: "Tools"
                    on_press:
                        toolbar.title = "Tools"
                        nav_drawer.set_state("close")
                        screen_manager.current = "tools_scr"